version: 2

sources:
  - name: some_source
    database: "EXAMPLE"
    schema: SOME_SCHEMA
    loaded_at_field: loadtime
    tables:
      - name: organisation
        identifier: actual_organisation_table_name
      - name: user
        identifier: actual_user_table_name

