repos:
    - repo: local
      hooks:
        - id: check-file-name
          name: Enforces SQL file naming conventions for dbt
          description: Prevents the usage of integers at the start of file names, causes errors in boilerplate generation in dbt
          language: system
          entry: bash
          stages: [commit]
          types: [sql]
          pass_filenames: true
          args: [".beau/scripts/check-file-name.sh"]
