name: {{cookiecutter.PROJECT_NAME}}
version: '0.1.0'
config-version: 2

profile: 'default'

require-dbt-version: [">=1.0.0", "<2.0.0"]

analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

vars:
  hash: SHA

models:
  {{cookiecutter.__PROJECT_SLUG}}:
      +materialized: table


# Add on-run-end hooks here e.g. for asset registration see https://xero.atlassian.net/wiki/spaces/DATATEAM/pages/269745989347/XTS+-+Asset+Registration+V2+with+DBT
